### ISSUE TITLE
Hide the inactive panels with React instead of CSS

### ISSUE THREAD

**Issue by Munter** [pedronauck/react-simpletabs#10]
Only actually rendering one single panel would reduce the amount of generated dom nodes.

It would also implement the very basic functionality of showing/hiding relevant content for people who might want to apply a different stylesheet. They wouldn't have to implement the `is-active` CSS themselves.

**Comment by pedronauck** [comment]
HI @Munter, I made this changes on the [last release](https://github.com/pedronauck/react-simpletabs/releases/tag/v0.3.1)

**Comment by Munter** [comment]
Awesome. Thank you very much :)
