### ISSUE TITLE
Ignore null/undefined children of Tabs component

### ISSUE THREAD

**Issue by PabloDiablo** [pedronauck/react-simpletabs#20]
I need to have some logic like this:

```javascript
<Tabs>
    <Tabs.Panel title="Tab 1">
        <SomeComponent data={this.props.data} />
    </Tabs.Panel>
    { hasTab2 ? (
        <Tabs.Panel title="Tab 2">
            <AnotherComponent data={this.props.data} />
        </Tabs.Panel>
    ) : null }
</Tabs>
```

This doesn't work. It throws an error and dies in `_getMenuItems` of the `Tabs` class as it can't read `props` of the null child. I'd suggest filtering out null/undefined children?

**Comment by pedronauck** [comment]
HI dude, thanks by the contribution... I made a little bugfix on e6a27be8. Now you can put you boolean logic as a children component.

Just a tip, I think that is more readable if you put the logic in a separated method, like that:

```javascript
getInitialState() {
  return {
    hasSomething: false
  };
},
render() {
  return (
    <Tabs>
      <Tabs.Panel title="Tab 1">
        <SomeComponent data={this.props.data} />
      </Tabs.Panel>
      {this._renderIfSomethingHappening()}
  </Tabs>
  );
},
_renderIfSomethingHappening() {
  if (this.state.hasSomething) {
    return (
      <Tabs.Panel title="Tab 2">
        <AnotherComponent data={this.props.data} />
      </Tabs.Panel>
    );
  }
}
```

Cheers :)

**Comment by PabloDiablo** [comment]
Hey @pedronauck. Thanks for that, that's awesome! Exactly what I needed :)

**Comment by pedronauck** [comment]
You're welcome @PabloDiablo :+1:
