### ISSUE TITLE
title with icon

### ISSUE THREAD

**Issue by pynixwang** [pedronauck/react-simpletabs#22]
or title with other component?

**Comment by pynixwang** [comment]
oh, sorry, maybe I can do it with css.

**Comment by pedronauck** [comment]
Oh, of course... I think so @pynixwang :)

**Comment by themre** [comment]
well... it would we more convenient to include prop icon, where you would provide for example fontawesome icon name or perhaps your custom svg. perhaps two props icon-class for example fontawesome or any other, and icon if you wanted to provide your custom icon. if any of those are not provided, img (or <i>) tag is not generated.

**Comment by themre** [comment]
Found a solution. You can pass HTML entities in props as an array:
https://facebook.github.io/react/docs/jsx-gotchas.html#html-entities
