### ISSUE TITLE
Uncaught TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by basarat** [pedronauck/react-simpletabs#34]
Stack : 

```
anonymous function)	@	react-simpletabs.js:154
React.createClass._getMenuItems	@	react-simpletabs.js:152
React.createClass.render	@	react-simpletabs.js:116
```

**Comment by basarat** [comment]
Straight after using this example : https://github.com/pedronauck/react-simpletabs#usage

**Comment by alex-wilmer** [comment]
Same issues as well.

**Comment by SepiG** [comment]
trying to render simple tab dynamically based on an array of objects and get this error too.

 <Tabs>
{ this.state.openTabsArray.map( 
        (tab) => { return <Tabs.Panel title={tab.name}></Tabs.Panel>  } 
) }
</Tabs>

**Comment by dherik** [comment]
Can you show your code? If you put something in <Tabs></Tabs> without wrapper in a <Tabs.Panel/>, you will get this error.

**Comment by basarat** [comment]
As far as I remember I just copied the code as it is from the example. Since it hasn't achieved much attention (this issue was really for the project owners) and I don't use this project, closing it to let someone else provide repo (perhaps a fiddle) :rose: 

Creating tabs in react is fairly simple (I wrote a bunch of these for http://alm.tools/) :rose:
