### ISSUE TITLE
Warning with react 0.12

### ISSUE THREAD

**Issue by rogierschouten** [pedronauck/react-simpletabs#8]
Copy-pasting the example code from README.md with react 0.12 yields the following warnings:

Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.

**Comment by pedronauck** [comment]
Hi @lllama, do you're seeing this bug yet?

**Comment by davide** [comment]
+1 Seeing the same error as @lllama while loading the module via webpack.

**Comment by davide** [comment]
"Cannot read property 'firstChild' of undefined" happens when 2 versions of react are loaded simultaneously (http://stackoverflow.com/a/27153167).
I'll submit a patch in a second.
